### ISSUE TITLE
Try to register an account using a username with profanity in it.

### ISSUE THREAD

**Issue by hjames82** [CrouchJumpInc/fangagement-public#10]
I first created a new fan account: 
user: cjjames
email: james@crouchjump.com

I then clicked the settings menu and it logged me out
I then created a new account:
user: fuckdick
email: fuckdick@gmail.com

It didn't say it didn't create the account, it just logged me in after submission, no errors or warnings. But when I went to post to see if it had created it or not, the user that was displayed is cjjames

Seems like a user session issue.

**Comment by hjames82** [comment]
I tried to register with the username: assholemac and it didn't flag me and
say it wouldn't work, it flashed a couple of screens and now is covered
with the full screen being solid white.

**Comment by DrVonDevious** [comment]
@hjames82 well the reason it doesn't block that name is because of the issue I shared about the scunthorpe problem. So right now the only names being blocked are the ones I have in a list, which won't block compound names but will block single banned words or names that we include like asshole. As for the second issue I'm not sure but if you can replicate it then I'd open a separate issue

**Comment by hjames82** [comment]
Thanks, the second issue is already reported and confirmed by several
testers.
